#ifndef cpu_hpp
#define cpu_hpp


class CPU {

    public:
        CPU();
        ~CPU();

    private:


        // Here goes the instructions ohboi
        void CPU::NOP();
        void CPU::LD_BC_d16(uint8_t operand);
        void CPU::LD_BC_E_A();
        void CPU::INC_BC();
        void CPU::INC_B();
        void CPU::DEC_B();
        void CPU::LD_B_d8(uint8_t operand);
        void CPU::RLCA();
        void CPU::LD_a16_E_SP(uint16_t operand);
        void CPU::ADD_HL_BC();
        void CPU::LD_A_BC_E();
        void CPU::DEC_BC();
        void CPU::INC_C();
        void CPU::DEC_C();
        void CPU::LD_C_d8(uint8_t operand);
        void CPU::RRCA();
        void CPU::STOP_0();
        void CPU::LD_DE_d16(uint8_t operand);
        void CPU::LD_DE_E_A();
        void CPU::INC_DE();
        void CPU::INC_D();
        void CPU::DEC_D();
        void CPU::LD_D_d8(uint8_t operand);
        void CPU::RLA();
        void CPU::JR_r8(uint8_t operand);
        void CPU::ADD_HL_DE();
        void CPU::LD_A_DE_E();
        void CPU::DEC_DE();
        void CPU::INC_E();
        void CPU::DEC_E();
        void CPU::LD_E_d8(uint8_t operand);
        void CPU::RRA();
        void CPU::JR_NZ_r8(uint8_t operand);
        void CPU::LD_HL_d16(uint8_t operand);
        void CPU::LD_HLI_E_A();
        void CPU::INC_HL();
        void CPU::INC_H();
        void CPU::DEC_H();
        void CPU::LD_H_d8(uint8_t operand);
        void CPU::DAA();
        void CPU::JR_Z_r8(uint8_t operand);
        void CPU::ADD_HL_HL();
        void CPU::LD_A_HLI_E();
        void CPU::DEC_HL();
        void CPU::INC_L();
        void CPU::DEC_L();
        void CPU::LD_L_d8(uint8_t operand);
        void CPU::CPL();
        void CPU::JR_NC_r8(uint8_t operand);
        void CPU::LD_SP_d16(uint8_t operand);
        void CPU::LD_HLD_E_A();
        void CPU::INC_SP();
        void CPU::INC_HL_E();
        void CPU::DEC_HL_E();
        void CPU::LD_HL_E_d8(uint8_t operand);
        void CPU::SCF();
        void CPU::JR_C_r8(uint8_t operand);
        void CPU::ADD_HL_SP();
        void CPU::LD_A_HLD_E();
        void CPU::DEC_SP();
        void CPU::INC_A();
        void CPU::DEC_A();
        void CPU::LD_A_d8(uint8_t operand);
        void CPU::CCF();
        void CPU::LD_B_B();
        void CPU::LD_B_C();
        void CPU::LD_B_D();
        void CPU::LD_B_E();
        void CPU::LD_B_H();
        void CPU::LD_B_L();
        void CPU::LD_B_HL_E();
        void CPU::LD_B_A();
        void CPU::LD_C_B();
        void CPU::LD_C_C();
        void CPU::LD_C_D();
        void CPU::LD_C_E();
        void CPU::LD_C_H();
        void CPU::LD_C_L();
        void CPU::LD_C_HL_E();
        void CPU::LD_C_A();
        void CPU::LD_D_B();
        void CPU::LD_D_C();
        void CPU::LD_D_D();
        void CPU::LD_D_E();
        void CPU::LD_D_H();
        void CPU::LD_D_L();
        void CPU::LD_D_HL_E();
        void CPU::LD_D_A();
        void CPU::LD_E_B();
        void CPU::LD_E_C();
        void CPU::LD_E_D();
        void CPU::LD_E_E();
        void CPU::LD_E_H();
        void CPU::LD_E_L();
        void CPU::LD_E_HL_E();
        void CPU::LD_E_A();
        void CPU::LD_H_B();
        void CPU::LD_H_C();
        void CPU::LD_H_D();
        void CPU::LD_H_E();
        void CPU::LD_H_H();
        void CPU::LD_H_L();
        void CPU::LD_H_HL_E();
        void CPU::LD_H_A();
        void CPU::LD_L_B();
        void CPU::LD_L_C();
        void CPU::LD_L_D();
        void CPU::LD_L_E();
        void CPU::LD_L_H();
        void CPU::LD_L_L();
        void CPU::LD_L_HL_E();
        void CPU::LD_L_A();
        void CPU::LD_HL_E_B();
        void CPU::LD_HL_E_C();
        void CPU::LD_HL_E_D();
        void CPU::LD_HL_E_E();
        void CPU::LD_HL_E_H();
        void CPU::LD_HL_E_L();
        void CPU::HALT();
        void CPU::LD_HL_E_A();
        void CPU::LD_A_B();
        void CPU::LD_A_C();
        void CPU::LD_A_D();
        void CPU::LD_A_E();
        void CPU::LD_A_H();
        void CPU::LD_A_L();
        void CPU::LD_A_HL_E();
        void CPU::LD_A_A();
        void CPU::ADD_A_B();
        void CPU::ADD_A_C();
        void CPU::ADD_A_D();
        void CPU::ADD_A_E();
        void CPU::ADD_A_H();
        void CPU::ADD_A_L();
        void CPU::ADD_A_HL_E();
        void CPU::ADD_A_A();
        void CPU::ADC_A_B();
        void CPU::ADC_A_C();
        void CPU::ADC_A_D();
        void CPU::ADC_A_E();
        void CPU::ADC_A_H();
        void CPU::ADC_A_L();
        void CPU::ADC_A_HL_E();
        void CPU::ADC_A_A();
        void CPU::SUB_B();
        void CPU::SUB_C();
        void CPU::SUB_D();
        void CPU::SUB_E();
        void CPU::SUB_H();
        void CPU::SUB_L();
        void CPU::SUB_HL_E();
        void CPU::SUB_A();
        void CPU::SBC_A_B();
        void CPU::SBC_A_C();
        void CPU::SBC_A_D();
        void CPU::SBC_A_E();
        void CPU::SBC_A_H();
        void CPU::SBC_A_L();
        void CPU::SBC_A_HL_E();
        void CPU::SBC_A_A();
        void CPU::AND_B();
        void CPU::AND_C();
        void CPU::AND_D();
        void CPU::AND_E();
        void CPU::AND_H();
        void CPU::AND_L();
        void CPU::AND_HL_E();
        void CPU::AND_A();
        void CPU::XOR_B();
        void CPU::XOR_C();
        void CPU::XOR_D();
        void CPU::XOR_E();
        void CPU::XOR_H();
        void CPU::XOR_L();
        void CPU::XOR_HL_E();
        void CPU::XOR_A();
        void CPU::OR_B();
        void CPU::OR_C();
        void CPU::OR_D();
        void CPU::OR_E();
        void CPU::OR_H();
        void CPU::OR_L();
        void CPU::OR_HL_E();
        void CPU::OR_A();
        void CPU::CP_B();
        void CPU::CP_C();
        void CPU::CP_D();
        void CPU::CP_E();
        void CPU::CP_H();
        void CPU::CP_L();
        void CPU::CP_HL_E();
        void CPU::CP_A();
        void CPU::RET_NZ();
        void CPU::POP_BC();
        void CPU::JP_NZ_a16(uint8_t operand);
        void CPU::JP_a16(uint8_t operand);
        void CPU::CALL_NZ_a16(uint8_t operand);
        void CPU::PUSH_BC();
        void CPU::ADD_A_d8(uint8_t operand);
        void CPU::RST_00H();
        void CPU::RET_Z();
        void CPU::RET();
        void CPU::JP_Z_a16(uint8_t operand);
        void CPU::PREFIX_CB();
        void CPU::CALL_Z_a16(uint8_t operand);
        void CPU::CALL_a16(uint8_t operand);
        void CPU::ADC_A_d8(uint8_t operand);
        void CPU::RST_08H();
        void CPU::RET_NC();
        void CPU::POP_DE();
        void CPU::JP_NC_a16(uint8_t operand);
        void CPU::CALL_NC_a16(uint8_t operand);
        void CPU::PUSH_DE();
        void CPU::SUB_d8(uint8_t operand);
        void CPU::RST_10H();
        void CPU::RET_C();
        void CPU::RETI();
        void CPU::JP_C_a16(uint8_t operand);
        void CPU::CALL_C_a16(uint8_t operand);
        void CPU::SBC_A_d8(uint8_t operand);
        void CPU::RST_18H();
        void CPU::LDH_a8_E_A(uint8_t operand);
        void CPU::POP_HL();
        void CPU::LD_C_E_A();
        void CPU::PUSH_HL();
        void CPU::AND_d8(uint8_t operand);
        void CPU::RST_20H();
        void CPU::ADD_SP_r8(uint8_t operand);
        void CPU::JP_HL_E();
        void CPU::LD_a16_E_A(uint16_t operand);
        void CPU::XOR_d8(uint8_t operand);
        void CPU::RST_28H();
        void CPU::LDH_A_a8_E(uint8_t operand);
        void CPU::POP_AF();
        void CPU::LD_A_C_E();
        void CPU::DI();
        void CPU::PUSH_AF();
        void CPU::OR_d8(uint8_t operand);
        void CPU::RST_30H();
        void CPU::LD_HL_SPIr8();
        void CPU::LD_SP_HL();
        void CPU::LD_A_a16_E(uint16_t operand);
        void CPU::EI();
        void CPU::CP_d8(uint8_t operand);
        void CPU::RST_38H();
        void CPU::CB_RLC_B();
        void CPU::CB_RLC_C();
        void CPU::CB_RLC_D();
        void CPU::CB_RLC_E();
        void CPU::CB_RLC_H();
        void CPU::CB_RLC_L();
        void CPU::CB_RLC_HL_E();
        void CPU::CB_RLC_A();
        void CPU::CB_RRC_B();
        void CPU::CB_RRC_C();
        void CPU::CB_RRC_D();
        void CPU::CB_RRC_E();
        void CPU::CB_RRC_H();
        void CPU::CB_RRC_L();
        void CPU::CB_RRC_HL_E();
        void CPU::CB_RRC_A();
        void CPU::CB_RL_B();
        void CPU::CB_RL_C();
        void CPU::CB_RL_D();
        void CPU::CB_RL_E();
        void CPU::CB_RL_H();
        void CPU::CB_RL_L();
        void CPU::CB_RL_HL_E();
        void CPU::CB_RL_A();
        void CPU::CB_RR_B();
        void CPU::CB_RR_C();
        void CPU::CB_RR_D();
        void CPU::CB_RR_E();
        void CPU::CB_RR_H();
        void CPU::CB_RR_L();
        void CPU::CB_RR_HL_E();
        void CPU::CB_RR_A();
        void CPU::CB_SLA_B();
        void CPU::CB_SLA_C();
        void CPU::CB_SLA_D();
        void CPU::CB_SLA_E();
        void CPU::CB_SLA_H();
        void CPU::CB_SLA_L();
        void CPU::CB_SLA_HL_E();
        void CPU::CB_SLA_A();
        void CPU::CB_SRA_B();
        void CPU::CB_SRA_C();
        void CPU::CB_SRA_D();
        void CPU::CB_SRA_E();
        void CPU::CB_SRA_H();
        void CPU::CB_SRA_L();
        void CPU::CB_SRA_HL_E();
        void CPU::CB_SRA_A();
        void CPU::CB_SWAP_B();
        void CPU::CB_SWAP_C();
        void CPU::CB_SWAP_D();
        void CPU::CB_SWAP_E();
        void CPU::CB_SWAP_H();
        void CPU::CB_SWAP_L();
        void CPU::CB_SWAP_HL_E();
        void CPU::CB_SWAP_A();
        void CPU::CB_SRL_B();
        void CPU::CB_SRL_C();
        void CPU::CB_SRL_D();
        void CPU::CB_SRL_E();
        void CPU::CB_SRL_H();
        void CPU::CB_SRL_L();
        void CPU::CB_SRL_HL_E();
        void CPU::CB_SRL_A();
        void CPU::CB_BIT_0_B();
        void CPU::CB_BIT_0_C();
        void CPU::CB_BIT_0_D();
        void CPU::CB_BIT_0_E();
        void CPU::CB_BIT_0_H();
        void CPU::CB_BIT_0_L();
        void CPU::CB_BIT_0_HL_E();
        void CPU::CB_BIT_0_A();
        void CPU::CB_BIT_1_B();
        void CPU::CB_BIT_1_C();
        void CPU::CB_BIT_1_D();
        void CPU::CB_BIT_1_E();
        void CPU::CB_BIT_1_H();
        void CPU::CB_BIT_1_L();
        void CPU::CB_BIT_1_HL_E();
        void CPU::CB_BIT_1_A();
        void CPU::CB_BIT_2_B();
        void CPU::CB_BIT_2_C();
        void CPU::CB_BIT_2_D();
        void CPU::CB_BIT_2_E();
        void CPU::CB_BIT_2_H();
        void CPU::CB_BIT_2_L();
        void CPU::CB_BIT_2_HL_E();
        void CPU::CB_BIT_2_A();
        void CPU::CB_BIT_3_B();
        void CPU::CB_BIT_3_C();
        void CPU::CB_BIT_3_D();
        void CPU::CB_BIT_3_E();
        void CPU::CB_BIT_3_H();
        void CPU::CB_BIT_3_L();
        void CPU::CB_BIT_3_HL_E();
        void CPU::CB_BIT_3_A();
        void CPU::CB_BIT_4_B();
        void CPU::CB_BIT_4_C();
        void CPU::CB_BIT_4_D();
        void CPU::CB_BIT_4_E();
        void CPU::CB_BIT_4_H();
        void CPU::CB_BIT_4_L();
        void CPU::CB_BIT_4_HL_E();
        void CPU::CB_BIT_4_A();
        void CPU::CB_BIT_5_B();
        void CPU::CB_BIT_5_C();
        void CPU::CB_BIT_5_D();
        void CPU::CB_BIT_5_E();
        void CPU::CB_BIT_5_H();
        void CPU::CB_BIT_5_L();
        void CPU::CB_BIT_5_HL_E();
        void CPU::CB_BIT_5_A();
        void CPU::CB_BIT_6_B();
        void CPU::CB_BIT_6_C();
        void CPU::CB_BIT_6_D();
        void CPU::CB_BIT_6_E();
        void CPU::CB_BIT_6_H();
        void CPU::CB_BIT_6_L();
        void CPU::CB_BIT_6_HL_E();
        void CPU::CB_BIT_6_A();
        void CPU::CB_BIT_7_B();
        void CPU::CB_BIT_7_C();
        void CPU::CB_BIT_7_D();
        void CPU::CB_BIT_7_E();
        void CPU::CB_BIT_7_H();
        void CPU::CB_BIT_7_L();
        void CPU::CB_BIT_7_HL_E();
        void CPU::CB_BIT_7_A();
        void CPU::CB_RES_0_B();
        void CPU::CB_RES_0_C();
        void CPU::CB_RES_0_D();
        void CPU::CB_RES_0_E();
        void CPU::CB_RES_0_H();
        void CPU::CB_RES_0_L();
        void CPU::CB_RES_0_HL_E();
        void CPU::CB_RES_0_A();
        void CPU::CB_RES_1_B();
        void CPU::CB_RES_1_C();
        void CPU::CB_RES_1_D();
        void CPU::CB_RES_1_E();
        void CPU::CB_RES_1_H();
        void CPU::CB_RES_1_L();
        void CPU::CB_RES_1_HL_E();
        void CPU::CB_RES_1_A();
        void CPU::CB_RES_2_B();
        void CPU::CB_RES_2_C();
        void CPU::CB_RES_2_D();
        void CPU::CB_RES_2_E();
        void CPU::CB_RES_2_H();
        void CPU::CB_RES_2_L();
        void CPU::CB_RES_2_HL_E();
        void CPU::CB_RES_2_A();
        void CPU::CB_RES_3_B();
        void CPU::CB_RES_3_C();
        void CPU::CB_RES_3_D();
        void CPU::CB_RES_3_E();
        void CPU::CB_RES_3_H();
        void CPU::CB_RES_3_L();
        void CPU::CB_RES_3_HL_E();
        void CPU::CB_RES_3_A();
        void CPU::CB_RES_4_B();
        void CPU::CB_RES_4_C();
        void CPU::CB_RES_4_D();
        void CPU::CB_RES_4_E();
        void CPU::CB_RES_4_H();
        void CPU::CB_RES_4_L();
        void CPU::CB_RES_4_HL_E();
        void CPU::CB_RES_4_A();
        void CPU::CB_RES_5_B();
        void CPU::CB_RES_5_C();
        void CPU::CB_RES_5_D();
        void CPU::CB_RES_5_E();
        void CPU::CB_RES_5_H();
        void CPU::CB_RES_5_L();
        void CPU::CB_RES_5_HL_E();
        void CPU::CB_RES_5_A();
        void CPU::CB_RES_6_B();
        void CPU::CB_RES_6_C();
        void CPU::CB_RES_6_D();
        void CPU::CB_RES_6_E();
        void CPU::CB_RES_6_H();
        void CPU::CB_RES_6_L();
        void CPU::CB_RES_6_HL_E();
        void CPU::CB_RES_6_A();
        void CPU::CB_RES_7_B();
        void CPU::CB_RES_7_C();
        void CPU::CB_RES_7_D();
        void CPU::CB_RES_7_E();
        void CPU::CB_RES_7_H();
        void CPU::CB_RES_7_L();
        void CPU::CB_RES_7_HL_E();
        void CPU::CB_RES_7_A();
        void CPU::CB_SET_0_B();
        void CPU::CB_SET_0_C();
        void CPU::CB_SET_0_D();
        void CPU::CB_SET_0_E();
        void CPU::CB_SET_0_H();
        void CPU::CB_SET_0_L();
        void CPU::CB_SET_0_HL_E();
        void CPU::CB_SET_0_A();
        void CPU::CB_SET_1_B();
        void CPU::CB_SET_1_C();
        void CPU::CB_SET_1_D();
        void CPU::CB_SET_1_E();
        void CPU::CB_SET_1_H();
        void CPU::CB_SET_1_L();
        void CPU::CB_SET_1_HL_E();
        void CPU::CB_SET_1_A();
        void CPU::CB_SET_2_B();
        void CPU::CB_SET_2_C();
        void CPU::CB_SET_2_D();
        void CPU::CB_SET_2_E();
        void CPU::CB_SET_2_H();
        void CPU::CB_SET_2_L();
        void CPU::CB_SET_2_HL_E();
        void CPU::CB_SET_2_A();
        void CPU::CB_SET_3_B();
        void CPU::CB_SET_3_C();
        void CPU::CB_SET_3_D();
        void CPU::CB_SET_3_E();
        void CPU::CB_SET_3_H();
        void CPU::CB_SET_3_L();
        void CPU::CB_SET_3_HL_E();
        void CPU::CB_SET_3_A();
        void CPU::CB_SET_4_B();
        void CPU::CB_SET_4_C();
        void CPU::CB_SET_4_D();
        void CPU::CB_SET_4_E();
        void CPU::CB_SET_4_H();
        void CPU::CB_SET_4_L();
        void CPU::CB_SET_4_HL_E();
        void CPU::CB_SET_4_A();
        void CPU::CB_SET_5_B();
        void CPU::CB_SET_5_C();
        void CPU::CB_SET_5_D();
        void CPU::CB_SET_5_E();
        void CPU::CB_SET_5_H();
        void CPU::CB_SET_5_L();
        void CPU::CB_SET_5_HL_E();
        void CPU::CB_SET_5_A();
        void CPU::CB_SET_6_B();
        void CPU::CB_SET_6_C();
        void CPU::CB_SET_6_D();
        void CPU::CB_SET_6_E();
        void CPU::CB_SET_6_H();
        void CPU::CB_SET_6_L();
        void CPU::CB_SET_6_HL_E();
        void CPU::CB_SET_6_A();
        void CPU::CB_SET_7_B();
        void CPU::CB_SET_7_C();
        void CPU::CB_SET_7_D();
        void CPU::CB_SET_7_E();
        void CPU::CB_SET_7_H();
        void CPU::CB_SET_7_L();
        void CPU::CB_SET_7_HL_E();
        void CPU::CB_SET_7_A();
}

#endif